### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mariusmitrofan** [cosmos/ethermint-archive#376]
## Description
The error appears when starting ethermint with "WS" options.
The error does not appear when the options are not used.

SAMPLE NON-WORKING:
```
root@tm-4132659651-1n58j:~# ethermint init /opt/genesis.json
INFO [01-17|17:25:54] Allocated cache and file handles         database=/root/.ethereum/ethermint/chaindata cache=16 handles=16
INFO [01-17|17:25:54] Writing custom genesis block
INFO [01-17|17:25:54] successfully wrote genesis block and/or chain rule set hash=2b72f9…d468ac

root@tm-4132659651-1n58j:~# ethermint --tendermint_addr tcp://TENDERMINT_HOST:46657 \
>                     --rpc --rpcapi eth,net,web3,personal,miner,admin,txpool \
>                     --abci_laddr tcp://0.0.0.0:46658 \
>                     --rpcaddr 0.0.0.0 \
>                     --rpcport 8545 \
>                     --ws \
>                     --wsaddr 0.0.0.0 \
>                     --wsport 30303 \
>                     --wsapi net,web3,eth \
>                     --wsorigins "*"
INFO [01-17|17:26:03] Starting peer-to-peer node               instance=ethermint/v1.6.7-stable/linux-amd64/go1.8.3
INFO [01-17|17:26:03] Allocated cache and file handles         database=/root/.ethereum/ethermint/chaindata cache=128 handles=1024
WARN [01-17|17:26:03] Upgrading chain database to use sequential keys
INFO [01-17|17:26:03] Initialised chain configuration          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> Engine: unknown}"
WARN [01-17|17:26:03] Ethash used in fake mode
WARN [01-17|17:26:03] Upgrading db log bloom bins
INFO [01-17|17:26:03] Bloom-bin upgrade completed              elapsed=363.691µs
INFO [01-17|17:26:03] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [01-17|17:26:03] Loaded most recent local header          number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:26:03] Loaded most recent local full block      number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:26:03] Loaded most recent local fast block      number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:26:03] Database conversion successful
INFO [01-17|17:26:03] Starting P2P networking
INFO [01-17|17:26:03] HTTP endpoint opened: http://0.0.0.0:8545
INFO [01-17|17:26:03] HTTP endpoint closed: http://0.0.0.0:8545
INFO [01-17|17:26:03] IPC endpoint closed: /root/.ethereum/geth.ipc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6acad2]

goroutine 1 [running]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/event.(*TypeMuxSubscription).Unsubscribe(0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/event/event.go:179 +0x22
github.com/tendermint/ethermint/ethereum.(*Backend).Stop(0xc42013bb30, 0xc4201d8d50, 0xc4203d1800)
	/ext-go/1/src/github.com/tendermint/ethermint/ethereum/backend.go:160 +0x2f
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/node.(*Node).Start(0xc4200a86c0, 0x0, 0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/node/node.go:223 +0xc00
github.com/tendermint/ethermint/ethereum.(*Node).Start(0xc4200a86c0, 0x0, 0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/ethereum/node.go:29 +0x2d
github.com/tendermint/ethermint/cmd/utils.StartNode(0xc4200a86c0)
	/ext-go/1/src/github.com/tendermint/ethermint/cmd/utils/utils.go:20 +0x2f
main.startNode(0xc420010420, 0xc4200a86c0)
	/ext-go/1/src/github.com/tendermint/ethermint/cmd/ethermint/ethermint.go:101 +0x40
main.ethermintCmd(0xc420010420, 0x0, 0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/cmd/ethermint/ethermint.go:30 +0x66
github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xdfa7a0, 0x10f1af8, 0xc420010420, 0xc420018360, 0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd4
github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420001380, 0xc420010160, 0x15, 0x16, 0x0, 0x0)
	/ext-go/1/src/github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x6ac
main.main()
	/ext-go/1/src/github.com/tendermint/ethermint/cmd/ethermint/main.go:111 +0x55
```

SAMPLE THAT IS WORKING (NOTHING ELSE CHANGED):
```
root@tm-4132659651-1n58j:~/.ethermint/ethermint# rm -rf /root/.ethereum/
root@tm-4132659651-1n58j:~# ethermint init /opt/genesis.json
INFO [01-17|17:25:54] Allocated cache and file handles         database=/root/.ethereum/ethermint/chaindata cache=16 handles=16
INFO [01-17|17:25:54] Writing custom genesis block
INFO [01-17|17:25:54] successfully wrote genesis block and/or chain rule set hash=2b72f9…d468ac
root@tm-4132659651-1n58j:~# ethermint --tendermint_addr tcp://TENDERMINT_HOST:46657 \
>                     --rpc --rpcapi eth,net,web3,personal,miner,admin,txpool \
>                     --abci_laddr tcp://0.0.0.0:46658 \
>                     --rpcaddr 0.0.0.0 \
>                     --rpcport 8545
INFO [01-17|17:29:43] Starting peer-to-peer node               instance=ethermint/v1.6.7-stable/linux-amd64/go1.8.3
INFO [01-17|17:29:43] Allocated cache and file handles         database=/root/.ethereum/ethermint/chaindata cache=128 handles=1024
INFO [01-17|17:29:43] Initialised chain configuration          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> Engine: unknown}"
WARN [01-17|17:29:43] Ethash used in fake mode
INFO [01-17|17:29:43] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [01-17|17:29:43] Loaded most recent local header          number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:29:43] Loaded most recent local full block      number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:29:43] Loaded most recent local fast block      number=0 hash=2b72f9…d468ac td=64
INFO [01-17|17:29:43] Starting P2P networking
INFO [01-17|17:29:43] HTTP endpoint opened: http://0.0.0.0:8545
INFO [01-17|17:29:43] RLPx listener up                         self="enode://97b639c39faea0fb627eb17271ec41dbf720e382859fd24b8f48c888d161202560f71c577c6e16fa435013a1860d1ae94fe2247370e6f02ad7e79b8a523cf1bc@[::]:30303?discport=0"
INFO [01-17|17:29:43] IPC endpoint opened: /root/.ethereum/geth.ipc
INFO [01-17|17:29:43] Waiting for tendermint endpoint to start err="Post http://tm:46657/status: dial tcp 10.59.243.32:46657: getsockopt: connection refused"
INFO [01-17|17:29:45] Starting ABCIServer                      module=abci-server impl=ABCIServer
INFO [01-17|17:29:45] Waiting for new connection...            module=abci-server
INFO [01-17|17:29:45] Accepted a new connection                module=abci-server
INFO [01-17|17:29:45] Waiting for new connection...            module=abci-server
INFO [01-17|17:29:45] Accepted a new connection                module=abci-server
INFO [01-17|17:29:45] Waiting for new connection...            module=abci-server
INFO [01-17|17:29:45] Accepted a new connection                module=abci-server
INFO [01-17|17:29:45] Waiting for new connection...            module=abci-server
INFO [01-17|17:29:48] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=680.279µs mgasps=0.000 number=1 hash=56498d…bd3a3b
INFO [01-17|17:29:50] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=447.239µs mgasps=0.000 number=2 hash=80d3a9…43519f
INFO [01-17|17:29:51] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=543.899µs mgasps=0.000 number=3 hash=8eb757…39a4ed
INFO [01-17|17:29:52] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=454.601µs mgasps=0.000 number=4 hash=a0d1d0…ca61
```

**Comment by mariusmitrofan** [comment]
UPDATE:

I've tried again with :
```
ethermint --tendermint_addr tcp://TENDERMINT_HOST:46657 \
                    --rpc --rpcapi eth,net,web3,personal,miner,admin,txpool \
                    --abci_laddr tcp://0.0.0.0:46658 \
                    --rpcaddr 0.0.0.0 \
                    --rpcport 8545 \
                    --ws \
                    --wsaddr 0.0.0.0 \
                    --wsapi net,web3,eth \
                    --wsorigins "*"
```
and this time it worked.

It seems as if when specifying the `--wsport 30303` part, it fails.

**Comment by mariusmitrofan** [comment]
Versions that I am running are:
```
ARG ETHERMINT_VERSION=0.5.3
ARG TENDERMINT_VERSION=0.14.0
```

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for latest work on ethermint
