### ISSUE TITLE
Ethermint install broken

### ISSUE THREAD

**Issue by kaladinlight** [cosmos/ethermint-archive#391]
## Description
To start, tendermint installs fine when running the command:
 `go get github.com/tendermint/tendermint/cmd/tendermint`

When I attempt to install ethermint using the same method:
`go get github.com/tendermint/ethermint/cmd/ethermint`

I get the following error output:
```
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:7:0:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go: In function ‘_duk_error’:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/duktape.h:510:127: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_error_raw((ctx), (duk_errcode_t) (err_code), (const char *) (DUK_FILE_MACRO), (duk_int_t) (DUK_LINE_MACRO), __VA_ARGS__), (duk_ret_t) 0)
                                                                                                                               ^
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:153:2: note: in expansion of macro ‘duk_error’
  duk_error(ctx, err_code, "%s", str);
  ^
# github.com/tendermint/ethermint/ethereum
go/src/github.com/tendermint/ethermint/ethereum/backend.go:54:26: too many arguments in call to eth.New
	have (*node.ServiceContext, *eth.Config, *EthState)
	want (*node.ServiceContext, *eth.Config)
go/src/github.com/tendermint/ethermint/ethereum/backend.go:67:55: cannot use NullBlockProcessor literal (type NullBlockProcessor) as type core.Validator in argument to ethereum.BlockChain().SetValidator:
	NullBlockProcessor does not implement core.Validator (wrong type for ValidateState method)
		have ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, *big.Int) error
		want ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, uint64) error
go/src/github.com/tendermint/ethermint/ethereum/backend.go:95:55: undefined: "github.com/tendermint/abci/types".Result
go/src/github.com/tendermint/ethermint/ethereum/backend.go:120:77: cannot use tmHeader.Time (type int64) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
go/src/github.com/tendermint/ethermint/ethereum/backend.go:121:21: cannot use tmHeader.GetNumTxs() (type int32) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:59:57: undefined: "github.com/tendermint/abci/types".Result
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:134:16: cannot convert *es.work.gp (type core.GasPool) to type big.Int
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:176:2: undefined: ethash.AccumulateRewards
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:177:20: cannot use ws.totalUsedGas (type *big.Int) as type uint64 in assignment
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:184:28: undefined: "github.com/tendermint/abci/types".Result
go/src/github.com/tendermint/ethermint/ethereum/eth_state.go:177:20: too many errors
```

**I then attempted to install from source with the following output for each attempt**

`make install`:
```
CGO_ENABLED=1 go install -ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse --short HEAD`" ./cmd/ethermint
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:7:0:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go: In function ‘_duk_error’:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/duktape.h:510:127: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_error_raw((ctx), (duk_errcode_t) (err_code), (const char *) (DUK_FILE_MACRO), (duk_int_t) (DUK_LINE_MACRO), __VA_ARGS__), (duk_ret_t) 0)
                                                                                                                               ^
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:153:2: note: in expansion of macro ‘duk_error’
  duk_error(ctx, err_code, "%s", str);
  ^
# github.com/tendermint/ethermint/ethereum
ethereum/backend.go:54:26: too many arguments in call to eth.New
	have (*node.ServiceContext, *eth.Config, *EthState)
	want (*node.ServiceContext, *eth.Config)
ethereum/backend.go:67:55: cannot use NullBlockProcessor literal (type NullBlockProcessor) as type core.Validator in argument to ethereum.BlockChain().SetValidator:
	NullBlockProcessor does not implement core.Validator (wrong type for ValidateState method)
		have ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, *big.Int) error
		want ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, uint64) error
ethereum/backend.go:95:55: undefined: "github.com/tendermint/abci/types".Result
ethereum/backend.go:120:77: cannot use tmHeader.Time (type int64) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
ethereum/backend.go:121:21: cannot use tmHeader.GetNumTxs() (type int32) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
ethereum/eth_state.go:59:57: undefined: "github.com/tendermint/abci/types".Result
ethereum/eth_state.go:134:16: cannot convert *es.work.gp (type core.GasPool) to type big.Int
ethereum/eth_state.go:176:2: undefined: ethash.AccumulateRewards
ethereum/eth_state.go:177:20: cannot use ws.totalUsedGas (type *big.Int) as type uint64 in assignment
ethereum/eth_state.go:184:28: undefined: "github.com/tendermint/abci/types".Result
ethereum/eth_state.go:177:20: too many errors
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 2
```

`go install $GOPATH/src/github.com/tendermint/ethermint/cmd/ethermint`:
```
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:7:0:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go: In function ‘_duk_error’:
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/duktape.h:510:127: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_error_raw((ctx), (duk_errcode_t) (err_code), (const char *) (DUK_FILE_MACRO), (duk_int_t) (DUK_LINE_MACRO), __VA_ARGS__), (duk_ret_t) 0)
                                                                                                                               ^
go/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:153:2: note: in expansion of macro ‘duk_error’
  duk_error(ctx, err_code, "%s", str);
  ^
# github.com/tendermint/ethermint/ethereum
../../ethereum/backend.go:54:26: too many arguments in call to eth.New
	have (*node.ServiceContext, *eth.Config, *EthState)
	want (*node.ServiceContext, *eth.Config)
../../ethereum/backend.go:67:55: cannot use NullBlockProcessor literal (type NullBlockProcessor) as type core.Validator in argument to ethereum.BlockChain().SetValidator:
	NullBlockProcessor does not implement core.Validator (wrong type for ValidateState method)
		have ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, *big.Int) error
		want ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, uint64) error
../../ethereum/backend.go:95:55: undefined: "github.com/tendermint/abci/types".Result
../../ethereum/backend.go:120:77: cannot use tmHeader.Time (type int64) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
../../ethereum/backend.go:121:21: cannot use tmHeader.GetNumTxs() (type int32) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
../../ethereum/eth_state.go:59:57: undefined: "github.com/tendermint/abci/types".Result
../../ethereum/eth_state.go:134:16: cannot convert *es.work.gp (type core.GasPool) to type big.Int
../../ethereum/eth_state.go:176:2: undefined: ethash.AccumulateRewards
../../ethereum/eth_state.go:177:20: cannot use ws.totalUsedGas (type *big.Int) as type uint64 in assignment
../../ethereum/eth_state.go:184:28: undefined: "github.com/tendermint/abci/types".Result
../../ethereum/eth_state.go:177:20: too many errors
```

*attempts with dependency install*

`glide install`
`go install $GOPATH/src/github.com/tendermint/ethermint/cmd/ethermint`:

```
# github.com/tendermint/ethermint/ethereum
../../ethereum/node.go:44:24: cannot use ctx (type *"github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1".Context) as type *"github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Context in argument to utils.SetNodeConfig
../../ethereum/node.go:53:23: cannot use ctx (type *"github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1".Context) as type *"github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Context in argument to utils.SetEthConfig
```

`make get_vendor_deps`
`go install $GOPATH/src/github.com/tendermint/ethermint/cmd/ethermint`:

This actually installs and creates and executable, but upon running, I get the following error:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils.NewApp(0xde51d3, 0x5, 0xe041f0, 0x24, 0xc420410bc8)
	/home/kevin/go/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils/flags.go:98 +0x225
```

I can't think of anything else at this point outside of starting to dig through source code and fix the apparent bug. Am I missing something? Hopefully you guys can help me figure this out.

Thank you.

**Comment by greg-szabo** [comment]
Can you add your `go env` results? Also, `go version`, please.

**Comment by kaladinlight** [comment]
Here is the `go env` results:
```GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kevin/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kevin/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build323032591=/tmp/go-build -gno-record-gcc-switches"
```

It looks like I was actually just able to get it working.

The solution was:
```
go get github.com/tendermint/ethermint
cd $GOPATH/src/github.com/tendermint/ethermint
make get_vendor_deps
make install
```

For whatever reason, the go install command wasn't working, but make install did...

Also to note, I started from a fresh state and attempted to use `glide install` before the `make install` without success. The `make get_vendor_deps` appears to be necessary.

**Comment by greg-szabo** [comment]
It's weird, because `make install` is calling `go install` but hey, if it works, it works. Changing directory is necessary for `make`, or what I usually do is `make -C $GOPATH/src/github.com/tendermint/ethermint get_vendor_deps install` which will tell make to change to the right directory before calling the targets.

**Comment by kaladinlight** [comment]
The `go install` did install and create the executable, but it resulted in the error I copied above when trying to run. The `make install` for whatever reason didn't give me the same run time error. Thanks for the help and I will keep that command you mentioned on hand for next time if I need it. Cheers!
